apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-deploy-2
  name: nginx-svc-2
  namespace: k8s-dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-deploy-2
  type: ClusterIP