apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy-1
  name: nginx-deploy-1
  namespace: k8s-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy-1
  strategy:
   type: RollingUpdate
   rollingUpdate:
    maxSurge: 20%
    maxUnavailable: 1
  template:
    metadata:      
      labels:
        app: nginx-deploy-1
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
